name: Build artifacts

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
          cache: true
          cache-dependency-path: "src/backend/go.sum"
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
          cache-dependency-path: "src/frontend/pnpm-lock.yaml"
      - run: pnpm install
        working-directory: src/frontend
      - run: pnpm build
        working-directory: src/frontend
      - run: |
          mkdir -p static
          cp -r ../frontend/dist static/
        working-directory: src/backend
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: latest
          workdir: src/backend
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}